accounts/urls.py
from django.urls import path, re_path
from . import views

app_name='accounts' #for namespacing our urls

urlpatterns = [
    re_path(r'^signup/$',views.signup_view, name="signup"),
    re_path(r'^login/$',views.login_view, name="login"),
    re_path(r'^logout/$',views.logout_view, name="logout"),
    ]

articles/urls.py
from django.urls import path, re_path
from . import views

app_name = 'articles'

urlpatterns = [
    re_path(r'^$',views.article_list, name="list"),
    re_path(r'^create/$',views.article_create, name="create"),
    re_path(r'^(?P<slug>[\w-]+)/$',views.article_detail, name="detail")
    #(?P<slug>) is named capturing group
]

djangonautic/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from . import views
#staticfiles_urlpatterns will setup urlpatterns & serves the static files
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# static will setup url patterns about  media-url &  media-directory ,
# and serves the media files
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^articles/',include('articles.urls')),
    re_path(r'^accounts/',include('accounts.urls')),
    re_path(r'^$',article_views.article_list,name='home'),
    re_path(r'^about/$',views.about)

]

#urlpatterns += staticfiles_urlpatterns()
urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    slugs = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png',blank=True)#blank=True means it can be optional
    author = models.ForeignKey(User,on_delete=models.CASCADE,default=None)

    #model methods:
    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + '...'

articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title','body','slugs','thumb']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
# Create your views here.

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            #log the user in
            login(request,user)
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request,'accounts/signup.html',{'form':form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            #login the user
            user = form.get_user()
            login(request,user)
            if 'nexts' in request.POST:
                return redirect(request.POST.get('nexts'))
            else:
                return redirect('articles:list')
    else:

        form = AuthenticationForm()
    return render(request,'accounts/login.html',{'form':form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('articles:list')

articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms

def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request,'articles/article_list.html',{'articles':articles})

def article_detail(request,slug):
    #return HttpResponse(slug)
    article = Article.objects.get(slugs=slug)
    return render(request,'articles/article_detail.html',{ 'article':article})

#this decorators will not allow to create blog if the user is not login and will redirect to login page
@login_required(login_url='/accounts/login/')
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST,request.FILES)
        if form.is_valid():
            # save article to db
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request,'articles/article_create.html',{'form':form})

djangonautic/views.py
#from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    return render(request,'homepage.html')

def about(request):
    return render(request,'about.html')

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
  <h1>Log in</h1>
  <form class="site-form" action="{% url 'accounts:login' %}" method="post">
    <!--csrf_token is for security purpose, to know that this request has been made by our app
    -->
    {% csrf_token %}
    {{ form }}
    {% if request.GET.next %}
      <input type="hidden" name="nexts" value="{{request.GET.next}}">
    {% endif %}
    <input type="submit" name="" value="LogIn">
  </form>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
  <h1>SignUp</h1>
  <form class="site-form" action="{% url 'accounts:signup' %}" method="post">
    <!--csrf_token is for security purpose, to know that this request has been made by our app
    -->
    {% csrf_token %}
    {{ form }}
    <input type="submit" name="" value="SignUp">
  </form>
{% endblock content %}

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block content %}

<div class="create-article">
    <h1>Create your blog here </h1>
    <!--ecnctype is reqd since we are uploading data(media) to the server-->
    <form class="site-form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form }}
      <input type="submit"  value="Create">
    </form>
</div>
<script src="/static/slugify.js"> </script>
{% endblock content %}

articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="article-detail">
    <div class="article">
      <div class="image">
        <img src="{{ article.thumb.url }}" />
      </div>

        <h2>{{ article.title }}</h2>
        <h3>Written by {{ article.author.username }}</h3>
        <p>{{ article.body }}</p>
        <p>{{ article.date }}</p>
    </div>
</div>
{% endblock %}

articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

{% block content %}
  <div class="wrapper">
    <h1>Article List</h1>
  </div>
    <div class="articles">
      {% for article in articles %}
        <div class="article">
          <h2> <a href="{% url 'articles:detail' slug=article.slugs %}">{{ article.title }}</a> </h2>
          <p> {{ article.snippet }} </p>
          <p> {{ article.date }} </p>
          <p class="author">added by {{article.author.username }}</p>
        </div>
      {% endfor %}
    </div>

{% endblock content %}

templates/about.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>AboutPage</title>
  </head>
  <body>
    <h1>About us</h1>
    <p>Django is fun</p>
  </body>
</html>

templates/base_layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Djangonauts</title>
        <link rel="stylesheet" href="{% static 'styles.css' %}">
    </head>
    <body>
        <header class="wrapper">
            <h1><a href="{% url 'home' %}"><img src="{% static 'logo.png' %}" alt="djangonautic" /></a></h1>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                    <li>
                        <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit">Logout</button>
                        </form>
                    </li>
                    <li><a href="{% url 'articles:create' %}" class="highlight">New Article</a></li>
                    {% else %}
                    <li><a href="{% url 'accounts:login' %}">Login</a></li>
                    <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <div class="wrapper">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

templates/homepage.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>HomePage</title>
  </head>
  <body>
    <h1>This is the homepage</h1>
    <p>Welcome to djangonautic</p>
  </body>
</html>